---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: botopsy
  description: "The central organization in our company."
spec:
  type: organization
  children: [infra]
---
apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: infra
spec:
  type: team
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: vidojeg
spec:
  memberOf: [infra]

###############
# SYSTEMS
###############
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: kubernetes
spec:
  owner: infra
